server:
  port:
    8080

spring:
  application:
    name:
      hotel-application
  datasource:
    url: jdbc:postgresql://localhost:5432/city-hotel
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka